package version python-defaults-2.4.3-10

diff --git a/debian/python.preinst.in b/debian/python.preinst.in
--- a/debian/python.preinst.in
+++ b/debian/python.preinst.in
@@ -21,7 +21,10 @@ case "$1" in
 		if ! $hook pre-rtupdate python$oldv @PVER@; then
 		    hb=$(basename $hook .rtupdate)
 		    echo >&2 "error running python pre-rtupdate hook $hb"
+		    echo >&2 "running python failed-pre-rtupdate hook $hb"
+		    $hook failed-pre-rtupdate python$oldv @PVER@
 		    errors=yes
+		    break
 		fi
 	    done
 	    [ -z "$errors" ] || exit 3
